### ISSUE TITLE
Use quick integration with SDK 2.4.6 and Redirect component from 3.2 together

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#100]
Hi!

Is it possible to use quick integration with SDK 2.4.6 and Redirect component 3.2 together? We're implementing payments with card tokens enrolled during quick integration. Now in order to implement 3DS1 for payment with card tokens we need to handle url redirections. Is it possible to handle them via the Redirect component from version 3.2? When I try to compile our app with the SDK 2.4.6. and redirect component 3.2 I get a gradle exception
```
ava.lang.RuntimeException: Duplicate class com.adyen.checkout.base.BuildConfig found in modules classes.jar (com.adyen.checkout:base-v3:3.2.0) and classes.jar (com.adyen.checkout:base:2.4.6)
```

**Comment by caiofaustino** [comment]
We never planned for the two versions to be used together, so that's not a scenario we have tested. More clashing issues like that might happen.

The redirect flow is pretty simple to implement, maybe you can give it a try? We basically call the redirect URL in a `CustomTabs` and then have an `IntentFilter` to handle the `returnUrl` and parse the result to send it to the `payments/details/` endpoint.
https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1#submit-a-payment
https://github.com/Adyen/adyen-android/blob/master/redirect/src/main/java/com/adyen/checkout/redirect/RedirectUtil.java#L90

Maybe in the future you can consider migrating from the SDK to the Drop-in component which can handle the tokenization and already has the Redirect component as a dependency, so you can have a more concise integration.

**Comment by przan** [comment]
Ok, thanks for hints and links.

I'm pretty sure we will migrate to 3+ version in the future, but now we're to close to our deadline.
