### ISSUE TITLE
ActionComponentData.getPaymentData() returns Nullable version on 3.2.1

### ISSUE THREAD

**Issue by Ehab4290** [Adyen/adyen-android#104]
ActionComponentData.getPaymentData() was returning `@NonNull` in version `3.2.0`. Now it returns `@Nullable` in version `3.2.1`. How should I handle `null` values in this case for `Adyen3DS2Component` and `RedirectComponent` as it is not mentioned in documentation?

**Comment by caiofaustino** [comment]
Hi @Ehab4290, sorry we forgot to add this change to our new change log file.

We did a small refactor on the `ActionComponentData` to become a `ModelObject`, which is how we handle serialization between `JSONObject` and the Java data classes. I think you mean the `getDetails()` changed, because on a `ModelObject` all properties are assumed to be `@Nullable` when we try to parse it from a `JSONObject`.

This means that now you can get the result of the `Adyen3DS2Component` and the `RedirectComponent` and call `ActionComponentData.SERIALIZER.serialize(result)` which will give you a `JSONObject` in a format you can send directly to your server.

From our implementation, even though the `getDetails()` is now `@Nullable` it should never return null. So if you get that scenario feel free to throw the user an error and contact us to investigate the issue.

**Comment by Ehab4290** [comment]
@caiofaustino I will do that. Thanks for clarification!
