### ISSUE TITLE
Adyen shows error message after payment succeeded (Drop-in SDK 3.2.1)

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#105]
**Steps to reproduce**
- Start a payment in an app with Adyen Drop-in SDK 3.2.1
- As payment method choose iDEAL, or any kind of payment method that will redirect you to an external app (e.g. the browser)
- While the external app is in the foreground and the original app is in the background, simulate Android killing the original app (for example by running `adb shell am kill <packagename>`)
- Now successfully complete the payment

(It may not work on a device where Android's "Custom Tabs" are available, since it will open the web content inside the app, instead of opening the browser.)

**Expected result**
The Adyen SDK starts the `resultHandlerIntent` and the user sees that the transaction was successful.

**Actual result**
Because the app has been killed in the background, it is recreated when the user comes back to it. This causes the Adyen SDK to end up in a bad state, and it shows a message saying "Error sending payment. Please try again.", _even though the payment actually succeeded_.

Screen recording:
![adyen_issue](https://user-images.githubusercontent.com/53077876/64026533-3db28a80-cb3f-11e9-8f04-cbae221111f6.gif)

**Comment by caiofaustino** [comment]
Thanks for the report, we will investigate :)

**Comment by caiofaustino** [comment]
Hi,
Can you please check what is the response you are getting from the details/ call?
I think this could be caused by missing the paymentData object on the details call.

**Comment by geertjan-tiqets** [comment]
Hi, I'm still trying to figure out what exactly is happening in our backend when I make the details call.

But on the client side I did notice that indeed paymentData is missing in this case.

When I make a normal, successful iDEAL payment, in `DropInService.makeDetailsCall()`, the `actionComponentData` contains:

`{"paymentData":"<snip>","details":{"payload":"<snip>"}}`

But when I reproduce the bug as described above, then `actionComponentData` contains:

`{"details":{"payload":"<snip>"}}`

(I snipped out some values for clarity.)

Hope this is helpful. I will get back to you with the response from the details call.

**Comment by caiofaustino** [comment]
Ahh OK, yeah this is indeed what I also saw in my tests here.

So basically the `paymentData` has the current payment state, and it needs to be passed to the `details/` call so that we know which payment those details are from. So if this was a redirect, what payment started that redirect and is waiting for the result for example.

The initial idea was that merchants should save that value on their backend, and then attach it to the object before sending the `details/` call. So we would send `{"details":<something>}` and then on your backend you would append the `paymentData` object before making the call.

But to make it a bit easier, if you return the paymentData inside the 'action' object, we temporarly store it in memory and already return it to you with the redirect result so that you can continue the payment directly. The problem is that in this case since the Activity was killed, we lose that temporary information.

I'm investigating an easy way to persist the data if the Activity gets destroyed to make a more consistent behavior, but in the meantime you can also do the backend check like I mentioned and add the `paymentData` from the previous `payments/` response before sending the `detais/` call.

I'll keep you posted.

**Comment by caiofaustino** [comment]
I implemented a fix for this, since you are using the Drop-in it should work out of the box.
Unfortunately it didn't make our 3.3.0 release from yesterday, so it will be available on the next one.

**Comment by caiofaustino** [comment]
Fix was just released on version 3.3.1, should be available in Jcenter as soon as the server sync.

**Comment by geertjan-tiqets** [comment]
Great, it's working! Thanks!
