### ISSUE TITLE
Crash when resultHandlerIntent contains a Parcelable (Drop-in SDK 3.2.1)

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#106]
**Steps to reproduce**
- Implement the payment flow as described in the Adyen documentation.
- Create a class that implements `Parcelable` (for example, the `MyParcelable` class from the [Android documentation](https://developer.android.com/reference/android/os/Parcelable)).
- When creating the `DropInConfiguration`, you set the parameter `resultHandlerIntent`. On that `Intent`, call `putExtra("some_key", myParcelable)`.
- Start the app and try to make a payment.

**Expected result**
Payment completes without crashes.

**Actual result**
After completing the payment the app crashes in `com.adyen.checkout.dropin.ui.DropInActivity.onActivityResult()`. Caused by `android.os.BadParcelableException: ClassNotFoundException when unmarshalling`.

I think the cause of the problem is here: https://github.com/Adyen/adyen-android/blob/master/drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt#L70
`Intent::class.java.classLoader` is used to read `resultHandlerIntent`, but that class loader is not aware of classes that are not part of the Android API.

As a workaround, I now put individual fields into `resultHandlerIntent`, instead of the Parcelable itself.

**Comment by caiofaustino** [comment]
Thanks for another great bug report, we will look into it.

**Comment by ArmanSo** [comment]
Hi @geertjan-tiqets 
I investigated on this issue and I came with result that can help you with it.

Let me explain first what's the issue:
When you passing `MyParcelable` to intent as extra what's happen that intent pass it's own `Parcel.obtain()` to  the `MyParcelable`'s `writeToParcel` function. so the function that been Override start to write data to intent's Parcel.
Till here everything is fine, but problem start when we want to add extra data to `resultHandlerIntent ` - [this line](https://github.com/Adyen/adyen-android/blob/master/drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt#L126)
Since `DropInActivity` have no clue what's type and class loader of the Parcelable's class it crash because can't find any class loader and we will see this error `ClassNotFoundException when unmarshalling: ...`
So what's unmarshalling exactly, unmarshalling mean that Intent wants to convert Parcel into new instant of `MyParcelable` object
```kotlin
companion object {
        @JvmField
        val CREATOR = object : Parcelable.Creator<MyParcelable> {
            override fun createFromParcel(parcel: Parcel) = MyParcelable(parcel)
            override fun newArray(size: Int) = arrayOfNulls<MyParcelable>(size)
        }
    }
```
There is fix for this issue by passing class loader with `setExtrasClassLoader`, but since class loaders are not Parcelable, the moment we pass `resultHandlerIntent` to other activities we're gonna lose that class loaders, so in that case we need to define those class loaders when we want to add extra data into `resultHandlerIntent` to allow intent to understand what kinda data defined

> Every time we add extras to intent `unparcel()` function get call from `BaseBundle.class`

But since you don't have access to that section of code it's impossible for `DropInActivity` to understand type of  Parcelable's class to get the class loader from it.
Indeed there is some dirty ways to use reflection to generate that class loaders, but we rather to not put that kinda code inside the project.

Other options that we have is

- Convert Parcelable class to ByteArray and pass it as ByteArray to intent
``` kotlin
object ParcelableUtil {
    fun marshall(parceable: Parcelable): ByteArray {
        val parcel = Parcel.obtain()
        parceable.writeToParcel(parcel, 0)
        val bytes = parcel.marshall()
        parcel.recycle()
        return bytes
    }

    fun unmarshall(bytes: ByteArray): Parcel {
        val parcel = Parcel.obtain()
        parcel.unmarshall(bytes, 0, bytes.size)
        parcel.setDataPosition(0) // This is extremely important!
        return parcel
    }

    fun <T> unmarshall(bytes: ByteArray, creator: Parcelable.Creator<T>): T {
        val parcel = unmarshall(bytes)
        val result = creator.createFromParcel(parcel)
        parcel.recycle()
        return result
    }
}
```
**[Credit](https://stackoverflow.com/questions/18000093/how-to-marshall-and-unmarshall-a-parcelable-to-a-byte-array-with-help-of-parcel?answertab=active#tab-top)**
``` kotlin
val resultIntent = Intent(this, MainActivity::class.java)
resultIntent.putExtra("KEY",ParcelableUtil.marshall(myParcelable))
```
``` kotlin
// read intent when it's back from DropInActivity
val byteArrays = intent.getByteArrayExtra("KEY")
val myParcelable = ParcelableUtil.unmarshall(byteArrays,MyParcelable.CREATOR)
```
- Use [Serializable](https://developer.android.com/reference/java/io/Serializable) beside of using Parcelable (I know that Serializable is slow and it's not suggested by Android but it's an option to use)
- Put individual fields into `resultHandlerIntent` as you implemented already.

Cheers

**Comment by geertjan-tiqets** [comment]
Thanks for the in-depth explanation. I see how it's tricky to solve this problem from your side, so if you want to just close this issue, it's fine with me. I'm happy with the workaround that I used.
