### ISSUE TITLE
CardView UI validation issue

### ISSUE THREAD

**Issue by kami4ka** [Adyen/adyen-android#118]
When CardView with CardComponent validates the card number it starts showing card type icon first:
![card_type_icon](https://user-images.githubusercontent.com/5595029/66726337-5535a080-ee6b-11e9-9777-46a9e9b83309.png)
But after switching focus to any other input field it shows validation error icon, but it is overlapped by the credit card type icon:
![overlaped_icon](https://user-images.githubusercontent.com/5595029/66726387-a6459480-ee6b-11e9-9b79-25b42b996e9c.png)

So the CardView looks very buggy and non-professional.

My suggestion is to hide the card type icon when the error icon appears.

**Comment by ArmanSo** [comment]
Hi @kami4ka 

Thanks for the feedback!

as I checked by default showing `Trailing icon` is disabled, so I guess you may overriding `Widget.MaterialComponents.TextInputLayout.*` style and that cause showing the error icon. or maybe it's because of different version of `com.android.support:appcompat-v7` or `com.google.android.material:material`

it would be great if you can provide us your more information about versions of design dependencies that you are using.

meanwhile if you want to have a quick fix I would suggest to override `AdyenCheckout.TextInputEditText`
and set `android:drawableRight` to `null`
```
<style name="AdyenCheckout.TextInputEditText">
    <item name="android:layout_width">match_parent</item>
    <item name="android:layout_height">@dimen/input_height</item>
    <item name="android:drawableRight">@null</item>
</style>
```

**Comment by kami4ka** [comment]
Hi, @ArmanSo 

material version is: `1.1.0-alpha09` 
androidx.appcompat is: `1.1.0-rc01`

Also no any overriding of `TextInputLayout`.

I've added the suggested style to my styles.xml, but it does not fix the issue.

**Comment by ArmanSo** [comment]
Thanks, @kami4ka 

First of all, we're not supporting any alpha versions!
Let me explain what happens and what is the issue:
In version `1.1.0-alpha09` of `com.google.android.material:material` - [link](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha09) they add this feature that shows error icon by default - [link](https://github.com/material-components/material-components-android/commit/3f73804b576fafe77febb75f06ac33b832588192) so that cause that issue that you had with card component. 
No worries tho! There is a fix for it, just override `AdyenCheckout.TextInputLayout` and set `errorIconDrawable` to null.

```
<style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxStrokeColor">@color/primaryColor</item>
    <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
    <item name="android:minHeight">@dimen/input_layout_height</item>
    <item name="errorIconDrawable">@null</item>
</style>
```

if that feature(By default showing error icon) ship to beta, we will adjust views to support that feature.

**Comment by kami4ka** [comment]
Thanks for the explanation, @ArmanSo 
The suggested style works and fixes the bug.
