### ISSUE TITLE
Button color issue in view_card_component_dropin.xml

### ISSUE THREAD

**Issue by mrdazhuk** [Adyen/adyen-android#125]
Looks like there is a bug in view_card_component_dropin.xml. 
There is the style **style="@style/AdyenCheckout.Button.Colored"** which is used with **AppCompatButton** and **Button**. All is fine with **AppCompatButton** (white text on blue background), but with **Button** the text is white on gray background. 

Probably there must be **AppCompatButton** instead of **Button** in **view_card_component_dropin.xml** and **fragmentdialog_component.xml**

**Comment by ArmanSo** [comment]
Hi @mrdazhuk 
Can you please send us your style file? I want to reproduce this issue before I want to take your suggestion.

Cheers.

**Comment by mrdazhuk** [comment]
Hi @ArmanSo )
My styles is pretty simple. App style is inherited from Theme.MaterialComponents.Light.NoActionBar. No other overridden styles. 

See attaches.   

<img width="135" alt="good_button" src="https://user-images.githubusercontent.com/2364283/67935104-dd3cd980-fbd1-11e9-8670-ae985a3ffb46.png">

<img width="138" alt="bug_button" src="https://user-images.githubusercontent.com/2364283/67935100-dca44300-fbd1-11e9-8bc1-c61cfec5f597.png">

Thanks)

**Comment by ArmanSo** [comment]
Thanks @mrdazhuk 

Issue fixed, and I switched all Buttons to `AppCompatButton` also I fixed issue with that white label on TextInputLayout.

it will publish in next version (Hopefully upcoming Monday)

**Comment by mrdazhuk** [comment]
OO, great)
Thank you=) 
Waiting....

**Comment by ArmanSo** [comment]
an update on TextInputLayout's label @mrdazhuk 
We're still using `com.android.support:appcompat-v7` to have backward compatibility with apps that are not sill using `com.google.android.material` and that bring some limitations, one of them is that issue as you can see with hint label.
So current implementation for the style of TextInputLayout is 
```
<style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxStrokeColor">@color/primaryColor</item>
    <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
    <item name="android:textColorHint">@color/primaryColor</item>
    <item name="android:minHeight">@dimen/input_layout_height</item>
</style>
```
By setting `hintTextAppearance` we would be able to change the hint label text color but this style changed in ` com.google.android.material`  to `hintTextColor`  and since we don't have access to that attribute, there is no clean way for us to set that as a default style. 

But there is an easy fix for it.
Just override `AdyenCheckout.TextInputLayout` in your style file to 
```
<style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxStrokeColor">@color/primaryColor</item>
    <item name="hintTextColor">@color/primaryColor</item>
    <item name="android:minHeight">@dimen/input_layout_height</item>
</style>
```
