### ISSUE TITLE
Express checkout flow for GooglePay

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-android#1279]
**Describe the bug**
I am trying to implement the Google Pay component by itself without DropIn and I am able to configure it. However, I need to set up the express checkout flow where the delivery address can be selected and after it is, we can update the delivery methods according to the delivery location. I was able to do this with the adyen-ios library for Apple Pay. However for Google Pay on Android, I am not able to find any docs or example code on how to do so. Is it possible at all? And if so can you point me in the right direction? Also a request to implement this in the example app for future reference for anyone using adyen-android.

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android 10
 - Browser: Flutter app
 - Version: 4.11.0

**Comment by jreij** [comment]
Hi @MewanWA , thanks for reaching out! Have you tried to configure the Google Pay component to show the billing and/or shipping address? Here's a code sample:

```kotlin
GooglePayConfiguration.Builder(shopperLocale, environment, clientKey)
            .setBillingAddressRequired(true)
            .setBillingAddressParameters(BillingAddressParameters(...)) // optional, allows extra configuration
            .setShippingAddressRequired(true)
            .setShippingAddressParameters(ShippingAddressParameters(...))  // optional, allows extra configuration
            .build()
```

This configuration is basically a mirror of Google Pay's JSON request objects, you can find more details [in this page](https://developers.google.com/pay/api/android/reference/request-objects). 

Hopefully this helps you get started! As for the example app, we're definitely aiming to add a Google Pay component sample integration at some point 👍

**Comment by mcg95** [comment]
Thank you @jreij for your quick response. I have added those configs but I am still unable to see the shipping methods section.

What I want to do on Android (Screenshot from a Website): 
<img width="612" alt="Screenshot 2023-08-01 at 10 52 26 AM" src="https://github.com/Adyen/adyen-android/assets/25398272/e28bed27-e164-4852-a5f4-8c56c65e8e22">

What I am shown right now on Android:
![Screenshot_1690858656](https://github.com/Adyen/adyen-android/assets/25398272/5bd4e57f-fdb7-4a6b-bd67-a63dad3b0cc6)

We want to implement quick/express checkout so that the addresses/shipping methods can be done on the Google Pay UI instead of on our application. Similar to that of Apple Pay express checkout functionality.

**Comment by jreij** [comment]
Hi, I believe I understand your use case now, there is an extra option on web called [Shipping options](https://developers.google.com/pay/api/web/reference/request-objects#ShippingOptionParameters) as part of their [Dynamic price updates](https://developers.google.com/pay/api/web/guides/tutorial#price-updates) flow which we call express checkout. However there doesn't seem to be any equivalent for that on Android from Google Pay's side, neither for the shipping options nor dynamic pricing.

**Comment by MewanWA** [comment]
@jreij Thank you very much for the information! If you could provide any documentation or link that could point Google mentioning that it is still not available would be helpful, but this is optional. If there is no documentation available regarding the ShippingOptions not being available on Android, feel free to close this ticket. Once again, thank you!
