### ISSUE TITLE
Indicative release date?

### ISSUE THREAD

**Issue by ethanmills** [Adyen/adyen-android#1300]
Hi folks, appreciate that this may not be something that you're able to share at the moment, but do you have an indicative release date for V5 of this library? I'm planning a migration from the old Checkout SDK and want to know if I should hold out for the simplified Sessions flow. Thanks in advance!

**Comment by jreij** [comment]
Hi @ethanmills, thanks for reaching out. We are very pleased to hear about the interest in v5! We've been putting a tremendous effort to bring lots of improvements to it as well as make it available ASAP.

As of now our plan is to release a beta in the upcoming weeks, then start preparing for a stable version. We would appreciate it if you can pick up the beta, try it out and give us your feedback so that we can polish it in preparation for the main release. I also think the beta and the stable release will not be very different so the eventual migration will be easier.

**Comment by ethanmills** [comment]
@jreij Thanks for the speedy reply, that's really useful! I'll be sure to share any feedback I have
