### ISSUE TITLE
Error message in payment failure

### ISSUE THREAD

**Issue by ehsanheidari67** [Adyen/adyen-android#132]
I'm trying to make a payment using `makePaymentsCall()` in the abstract class `DropInService`. When the payment is successful it's fine. But if there is an error in the payment, I need to show a proper error message to the user based on the reason of error. So I try to create and return an instance of `CallResult`:

> CallResult(CallResult.ResultType.ERROR, "The reason of the failure")

But I see that the library just logs this message and shows a Toast with a constant error message from the strings.xml resource 
`Toast.makeText(this@LoadingActivity, R.string.payment_failed, Toast.LENGTH_LONG).show()`

It would be nice if the library is able to display a dynamic message to the user rather than a constant one, in case of error.

**Comment by caiofaustino** [comment]
Hi @ehsanheidari67,
Thanks for reaching out, indeed that is the plan behind the `CallResult`, to allow you to pass the error message back to the user, this is definitely in our backlog but we still need to work on what's the best way to present the error. Depending on the scenario, a Toast is probably not the best approach.

This is the first tome someone actually requested the functionality, so I'll try to prioritize here and come back to you.

**Comment by caiofaustino** [comment]
Hey there, we just released version `3.6.0` with a change in this functionality.

To make sure we don't break any existing implementation I decided to create new `ResultType`, so now there is `CallResult.ResultType.ERROR_WITH_MESSAGE`.

All error messages will now be displayed in a regular AlertDialog instead of the Toast, and there is also a new constructor parameter on the `ResultType` where you can indicate if you would like to dismiss the DropIn flow after displaying the error or not.

Please give it a try and let me know, any feedback is appreciated :)

**Comment by caiofaustino** [comment]
Closing the issue, feel free to reopen it if you have any problems.
