### ISSUE TITLE
GooglePay and onActivityResult issue

### ISSUE THREAD

**Issue by kami4ka** [Adyen/adyen-android#133]
Hello.

I'm trying to implement GooglePay via GooglePayComponent component and have faced another problem with redirection back to my app with following steps:
1. I'm checking if Google Pay is available for the shopper (GooglePayProvider.isAvailable)
2. I'm starting the payment via  `startGooglePayScreen`
3. Observing the following screen: 
![Image from iOS (5)](https://user-images.githubusercontent.com/5595029/68961568-5e53bd80-07db-11ea-8303-3ac992d90035.jpg)
4. Closing this screen by tapping on top left corner close button.

The result: no invocation of `onActivityResult` inside my code. 
Can I somehow track the closing of the Google Pay screen to handle it inside my app?

**Comment by kami4ka** [comment]
Also after trying to pay with real card in default google pay environment "ENVIRONMENT_TEST" I didn't receive any intent too (even with no chargeable token, as said in the following doc: https://developers.google.com/pay/api/android/guides/test-and-deploy/integration-checklist)

**Comment by caiofaustino** [comment]
Hey @kami4ka,
Sorry for the delay. I tested on my side and the `onActivityResult` was called normally.
When calling `startGooglePayScreen(Activity activity, int requestCode)` the activity and request code that you passed are the ones that will receive the result from the Google Pay SDK. Maybe can you share your code to see if I can spot anything?

The `onActivityResult` is also where you should receive the result with the token to pass back to the component like this
`googlePayComponent.handleActivityResult(resultCode, data)`
You can also check the example on our docs:
https://docs.adyen.com/payment-methods/google-pay/android-component#show-google-pay-in-your-payment-form

Hope it helps.

**Comment by kami4ka** [comment]
So I'm starting google pay in my fragment:
`startGooglePayScreen(unsafeActivity, GOOGLE_PAY_REQUEST_CODE)`
and subscribing to result by implementing the:
```
 override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == GOOGLE_PAY_REQUEST_CODE) {
            googlePayComponent?.handleActivityResult(resultCode, data)
        }
    }
```
so using the case described at the first and second messages i have no invokation of even `super.onActivityResult(requestCode, resultCode, data)` (checked by debugger)

**Comment by caiofaustino** [comment]
Hmmm, I just noticed that `Fragment` class also has the `onActivityResult` method available to override, I didn't know that. But it seems that for it to receive the result, the `startActivityForResult` must have also been called from the `Fragment`.

In the case of GooglePay, we are not calling `startActivityForResult`, instead we use the GooglePay SDK to start the flow, and it only accepts an `Activity` as parameter.
Check docs [here](https://developers.google.com/android/reference/com/google/android/gms/wallet/AutoResolveHelper.html#resolveTask(com.google.android.gms.tasks.Task%3CTResult%3E,%20android.app.Activity,%20int))

So I think to fix this you just need to pass the Fragments parent activity, and override the `onActivityResult` there instead. Then maybe pass the result intent back to the Fragment so that it can pass it back to the Component and keep handling everything there.

Let me know if that works :)

**Comment by kami4ka** [comment]
So, correct me, please, if I'm wrong. You're suggesting try to catch the result in parent activity after starting google pay screen from fragment with passing parent activity to `startGooglePayScreen`. Am I right?

**Comment by caiofaustino** [comment]
Yeah I think that's right. You need to have `onActivityResult` on the same instance as that `unsafeActivity` that you are passing as the parameter.

**Comment by caiofaustino** [comment]
Did you manage to make the flow work? Please let me know and I can close the issue :)

**Comment by kami4ka** [comment]
@caiofaustino thanks for reminding :)
Will be able to check it from monday and contact you ASAP

**Comment by kami4ka** [comment]
@caiofaustino you're right. The only way to receive this request is only from activity.
The related StackOverflow issue: https://stackoverflow.com/questions/54020576/google-pay-autoresolvehelper-resolvetask-not-calling-onactivityresult-in-fragm
