### ISSUE TITLE
Components/Sessions documentation seems buggy

### ISSUE THREAD

**Issue by jmartinVMLYR** [Adyen/adyen-android#1348]
**Describe the bug**
Trying to complete a payment flow with Android components on either 4.13.2 or 5.0.0-beta01, but the documentation is either non-existent or my google skills are too weak to crack the code.

Also, while I have you here, is there a target release date for 5.0.0?

**To Reproduce**
1. Go to [Build your integration page](https://docs.adyen.com/online-payments/build-your-integration)
2. Click on `Android` + `Components`
3. Scroll down to `Choose Components version`
4. Note that the latest is 4.11.0
6. Scroll down to `How it works`
7. Note that the sequence diagram is for Drop-in

**Expected behavior**
I would expect to find documentation for available SDK versions here. As a team, we want to use sessions, so really looking for that 5.0.0 documentation. And the iOS documentation is pretty clear. But I can't find parallel instructions for Android.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Ventura, v. 13.5.2
 - Browser: Chrome, v. 116.0.5845.179

**Comment by OscarSpruit** [comment]
Hi @jmartinVMLYR, thank you for opening this issue! Since v5 is still in beta and the documentation is in progress, it is not easy to find the pages. However, we do have a first iteration available [here](https://docs.adyen.com/online-payments/build-your-integration/android-5-0-0-beta-release/components/). Please bear in mind that the page is in need of some improvements.

We don't have a target date for the stable 5.0.0 release yet. Currently, we are gathering feedback on the beta, so we can make a stable release as soon as possible.

Thank you for letting us know about the mistakes on the 4.x.x Components page! This will help us improve it.

In case the documentation is not clear, you have any feedback or any other questions feel free to let us know here.

**Comment by OscarSpruit** [comment]
Hi @jmartinVMLYR, we released the stable 5.0.0 version! We also updated [the documentation](https://docs.adyen.com/online-payments/build-your-integration/?platform=Android&integration=Drop-in&version=5.0.0). Please let us know if anything in the documentation is unclear.
