### ISSUE TITLE
Failure in Release Build after Gradle 8.4 Upgrade and Adyen SDK Migration to version 4.13.3 (ERROR: R8 Missing Class)

### ISSUE THREAD

**Issue by ShimaZN** [Adyen/adyen-android#1394]
**Describe the bug**
After upgrading our Gradle version to 8.4 and migrating the Adyen SDK from version 3.x.x to version 4.13.3, attempting to build the release version resulted in failure. The issue is specifically encountered when running the task 'minifyWithR8'.

**To Reproduce**

Upgrade Gradle to version 8.4.
Migrate Adyen SDK from version 3.x.x to version 4.13.3.
Attempt to build the release version with minifyEnabled true
Observe the failure.

**Expected behavior**
The build should be successful without errors.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
The error message received during the build failure is as follows:
`ERROR: R8: Missing class com.adyen.threeds2.ThreeDS2Service (referenced from: com.adyen.checkout.components.GenericComponentState com.adyen.checkout.bcmc.BcmcComponent.createComponentState() and 1 other context)`

I am using the following Proguard rules:
```
# Adyen
-keep class com.adyen.checkout.components.model.** { *; }
-keep class com.adyen.threeds2.** { *; }
-keepclassmembers public class * implements com.adyen.checkout.components.PaymentComponent {
 public <init>(...);
}
-keepclassmembers public class * implements com.adyen.checkout.components.ActionComponent {
 public <init>(...);
}
```
Additionally, our project is not using R8 in full mode, as specified in the configuration:
```
# Disable full mode, having the previous setup as before
#https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes
android.enableR8.fullMode=false
```

It's worth mentioning that testing with Gradle version 7.x does not result in any issues.

**Comment by OscarSpruit** [comment]
Hi @ShimaZN, thank you for reaching out! It seems like the dependency for 3DS2 is missing. Could you add `implementation "com.adyen.checkout:3ds2:4.13.3"` to your build.gradle and try again?

Just a FYI, since you're migrating from 3.x.x; version 5.0.1 just came out and it's even easier to integrate with compared to version 4.x.x. Give it a try if you want to!

**Comment by ShimaZN** [comment]
Hi @OscarSpruit 
Thanks for your response. I added it, and the problem is fixed. 
May I ask why we need this dependency only for the release build when 'minifyWithR8' is running? Because for the debug build, I didn't face any problems.

**Comment by OscarSpruit** [comment]
That is a good question 🤔 My theory is that R8 needs the full 3DS2 dependency, because it's trying to obfuscate its classes. 3DS2 is a `compileOnly` dependency of the bcmc module, so that probably causes the classes not to be available during R8.

It sounds a bit like a bug on the AGP/R8 side in my opinion.

**Comment by ShimaZN** [comment]
Yes, it sounds a bit like a bug to me too! 
For now, I've included this dependency in our dependencies and added a comment for future reference, so we don't forget why it was added. If you could consider adding this dependency to your module that requires it, it would be beneficial for others using the SDK. One question: Will we still need this dependency in version 5 as well?

**Comment by OscarSpruit** [comment]
Just found this in [the AGP release notes](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#enforced-changes), so it seems to be by design. Setting this flag to false may also fix the issue (if you do not need 3DS2 this would be the better option).

Also tried to reproduce it with version 5.0.1 and I was not able to get the exact same error, but a similar error caused by `kotlinx.parcelize` not being a dependency of my sample project.

We will investigate more if there is something we can do about this. 

![image](https://github.com/Adyen/adyen-android/assets/17701279/596317a3-68de-436b-b523-5e1179c71827)

**Comment by ShimaZN** [comment]
Thanks @OscarSpruit
