### ISSUE TITLE
makeDetailsCall not called after redirect

### ISSUE THREAD

**Issue by JoeCiou** [Adyen/adyen-android#144]
I am making a 3DS1 auth flow. when I redirect to the app, the app doesn't call makeDetailsCall.
I use debug mode found the DropInActivity is destroyed before onNewIntent is called.
any idea why that happens?

Thanks in advance for your help.

**Comment by caiofaustino** [comment]
Destroyed before onNewIntent? I've not seen that behavior before.
Is the DropInActivity being started from the browser intent of the `returnUrl` you sent?

**Comment by JoeCiou** [comment]
Yes, I explain my work. I refer the document to return action with `returnUrl` in `makePaymentsCall` and add an `IntentFilter` to the `Activity` that will handle the `returnUrl`. But after I submit 3DS1 auth and redirect to app, the `makeDetailsCall` is not called and the `DropInActivity` is destroyed. By the way, I use Flutter plugin to bridge the SDK.

**Comment by caiofaustino** [comment]
Ah OK, so maybe we are not very clear on the Documentation about this difference.
The `IntentFilter` is only needed if you are using the separate Components, specifically the `RedirectComponent` to make your payment flow.
On the Drop-in solution, we handle the redirect flow for you, so the `DropInActivity` already has the `IntentFilter` setup to handle the 3DS1 response for you automatically. You only need to make sure to send the correct `returnUrl` in the `/payments` which you already seem to be doing right.

So probably in this case your own `IntentFilter` is getting the redirect result instead of the DropInActivity. Try removing that and see if the behavior changes.

**Comment by JoeCiou** [comment]
Work! I completely can't imagine add `IntentFilter` will cause this. Thanks for your accurate and quick answer.
