### ISSUE TITLE
PaymentMethodDetails Serialization

### ISSUE THREAD

**Issue by kami4ka** [Adyen/adyen-android#147]
Later I've seen in this repo examples usage of this Moshi adapter implementation
 ```
 PolymorphicJsonAdapterFactory.of(PaymentMethodDetails::class.java, PaymentMethodDetails.TYPE)
                .withSubtype(CardPaymentMethod::class.java, CardPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(IdealPaymentMethod::class.java, IdealPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(EPSPaymentMethod::class.java, EPSPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(DotpayPaymentMethod::class.java, DotpayPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(EntercashPaymentMethod::class.java, EntercashPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(OpenBankingPaymentMethod::class.java, OpenBankingPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(GooglePayPaymentMethod::class.java, GooglePayPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(SepaPaymentMethod::class.java, SepaPaymentMethod.PAYMENT_METHOD_TYPE)
                .withSubtype(GenericPaymentMethod::class.java, "other")
        )
            .add(
                PolymorphicJsonAdapterFactory.of(Action::class.java, Action.TYPE)
                    .withSubtype(RedirectAction::class.java, RedirectAction.ACTION_TYPE)
                    .withSubtype(Threeds2FingerprintAction::class.java, Threeds2FingerprintAction.ACTION_TYPE)
                    .withSubtype(Threeds2ChallengeAction::class.java, Threeds2ChallengeAction.ACTION_TYPE)
                    .withSubtype(QrCodeAction::class.java, QrCodeAction.ACTION_TYPE)
                    .withSubtype(VoucherAction::class.java, VoucherAction.ACTION_TYPE)
            )
            .build()
```

But looks like it been removed and now it's not working for Google Pay (PaymentMethodDetails serializes in the wrong way). What is the suggested way to use it now?

UPD: I realized also a few more additional lines:
```
// TODO GooglePayPaymentMethod token has a variable name that is not compatible with Moshi
        request.remove("paymentMethod")
        request.put("paymentMethod", PaymentMethodDetails.SERIALIZER.serialize(paymentsRequest.paymentMethod))
```
So what about this TODO status? Will it be fixed in the future? `PolymorphicJsonAdapterFactory` looks so handy with good architectures and in this case Google Pay breaks the whole idea.

**Comment by caiofaustino** [comment]
Hey @kami4ka,

We try to keep our Model classes compatible with Moshi and Gson since they are common libraries that lots of people use, but we cannot add them as dependencies ourselves, so we can't add the annotations that would fix those incompatibilities. That `TODO` was on our example app while we were testing the compatibility, and had to do workarounds like that to have it working.

Unfortunately some keys, like the one on GooglePay are not compatibles, so for example "google.token" as the Json key cannot be automatically matched to the variable name, because I can't have the dot on the variable.

We haven't figured out a way to support those cases yet, so the only official way to serialize Model objects between our java classes and JSON is using the `SERIALIZER` static object on each class that returns a `JSONObject`. You can then use Moshi or Gson with the JSONObject.

Hope that helps.

**Comment by kami4ka** [comment]
Hi, @caiofaustino, thanks for the reply.

Ok, I'll work on the adapter solution and will try to share it later.
