### ISSUE TITLE
`OrderResponse` is null when receiving an `Authorised` result code from the `SessionDropInResult`

### ISSUE THREAD

**Issue by gabrielglbh** [Adyen/adyen-android#1472]
**Describe the bug**
I am creating a DropIn following the documentation. Everything is working as expected, the payments are being performed but when I want to display the amount the user has paid, the object `order` is null. With this, I am not able to display nothing.

**To Reproduce**
1. Follow the steps on the [docs](https://docs.adyen.com/online-payments/build-your-integration/?platform=Android&integration=Drop-in&version=5.2.0) until [Step 4](https://docs.adyen.com/online-payments/build-your-integration/?platform=Android&integration=Drop-in&version=5.2.0).
2. When listening to the `onDropInResult` callback, in the `SessionDropInResult.Finished` case, try to access the `order` from `sessionDropInResult.result.order`.
3. The `order` will be null.

**Expected behavior**
When receiving the `SessionDropInResult` from the `onDropInResult` callback, `order` should not be null and the `amount` should be the one that the user paid.

**Smartphone:**
 - Device: Pixel 3a
 - OS: API 34
 - Adyen Version: `drop-in-compose:5.2.0`

**Additional context**
I crossed verified the code with iOS and the `AdyenSession` context is correctly receiving the `amount`.

**Comment by jreij** [comment]
Hi @gabrielglbh , thanks for reaching out. To clarify one point first, the `order` object is only intended for a specific flow called partial payments flow, so it is not intended for this use case and will be null. We'll add some code docs to clarify this.

As for the amount, you are right indeed, we do not propagate it as part of the `SessionPaymentResult` object. That is simply because the amount is known on your side, you need to set it when you call the `/sessions` endpoint before launching drop-in and it cannot change throughout the flow so it is guaranteed to be the same amount that you initialized the payment with.

Is there any reason why you don't/can't have access to this amount in your Android app?

**Comment by gabrielglbh** [comment]
Hello @jreij!! Thank you for the quick answer! 

I was expecting something like that when I was not receiving the `order`. Sounds reasonable. I can just propagate the `amount` from my side, yup, no problems at all. The only reason I did not do it was because of the `order` variable, I was just confused.

Thank you for the clarification!

**Comment by jreij** [comment]
@gabrielglbh happy to help! I can see how the `order` field can be confusing, we will definitely be improving the documentation there 👍
