### ISSUE TITLE
[v5.3.0] Using 3DS2 and Session when a transaction is `Refused`, the `SessionDropInCallback` is not called

### ISSUE THREAD

**Issue by gabrielglbh** [Adyen/adyen-android#1532]
**Describe the bug**
When coming back from the bank verification using Session and DropIn, if the transaction somehow gets `Refused`, when coming back to the main app, the DropIn dismisses but the `SessionDropInCallback` is not called at all. 

Only happens in Android 10. I have tried it in Android 14 and it goes smoothly as butter.

**To Reproduce**
1. Pay X amount of money with 3DS2 method
2. Input the bank verification code in the activity
3. The DropIn should vanish without the callback getting called

**Expected behavior**
When coming back to the app from the bank verification page, I expect the flow to always go through `SessionDropInCallback`.

**Screenshots**

**In Android 10**
https://github.com/Adyen/adyen-android/assets/26835924/18f9491d-688e-463a-ab1c-b75d44682531

As you can see in the video, when returning back from the verification screen, the DropIn completely disappears and the `SessionDropInCallback` is not called (thus the appearance of the 2 or 3 other DropIns - expected). I know the code is `Refused` because when I dismiss the new DropIns, the failed one actually completes. Strange behaviour.

**In Android 14**
https://github.com/Adyen/adyen-android/assets/26835924/133a8e4f-0e43-4836-9a1b-1f24756c9fbc

Works fine and the callback gets executed and the expected error screen is shown. 

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: API 29 - Android 10 **ONLY**. In other versions of Android the callback works just fine.
 - Browser in which the 3DS2 gets active: Google Chrome

**Comment by araratthehero** [comment]
Hi @gabrielglbh, thanks for opening the bug report.

I've followed the steps you provided but couldn't replicate the issue on an emulator and using SDK version `5.3.0`.

To proceed further, could you please provide some additional information?
- Can you specify the SDK version you're using?
- Please share the code showing how you pass the `SessionDropInCallback` to Drop-in.
- Any specific device parameters that could help in creating the correct emulator instance.
- Any other relevant information you believe would assist in reproducing the issue.

**Comment by araratthehero** [comment]
@gabrielglbh thanks for sharing the details. 

I was still not able to reproduce the issue, but I have some ideas which can help:

- Could you pass the `checkoutConfiguration` as it is to `DropIn.startPayment` as mentioned in the "Start Drop-in" code sample [in the docs](https://docs.adyen.com/online-payments/build-your-integration/?platform=Android&integration=Drop-in&version=5.3.0&tab=no-compose-launch_2#launch-and-show)? These methods are not documented, because they are not supposed to be used for launching drop-in or creating components. We already added a warning against using them in the [5.3.0 release notes](https://github.com/Adyen/adyen-android/releases/tag/5.3.0) and we'll make them internal in the next release.
Similarly for `addCardConfiguration()`. The `CheckoutConfiguration.getCardConfiguration()` will also be made internal.

I've also noticed that below API 30 the recomposition works differently in Compose.

-  Could you check if by any chance the `DropIn.startPayment` gets called twice? Because if you use the same `dropInLauncher` to launch drop in more than once, it will only return result for the first launch.
- I am not sure where you create the `dropInLauncher`, but I would try creating an instance of `SessionDropInCallback` outside of Compose (Can be in your `ViewModel` or `Activity`) and pass it to your compose screens. This way a single instance of `SessionDropInCallback` will be used when recomposition happens.

Could you make the changes and let me know if it resolves the issue?

**Comment by gabrielglbh** [comment]
@araratthehero Thank you for the tips! I will try them next week and I will let you know ASAP!

**Comment by gabrielglbh** [comment]
@araratthehero It seemed that the trigger to the `DropIn.startPayment` was getting called various times even before the `SessionDropInCallback` was performed. Adding a control variable solved the issue. And I also applied the suggested change from the docs :) Thank you very much!

**Comment by araratthehero** [comment]
Hi @gabrielglbh, I am happy to hear it worked for you.
