### ISSUE TITLE
[5.0.1] Keyboard doesnt push up dropin bottomsheet fully for Compose, hiding fields and buttons.

### ISSUE THREAD

**Issue by mikeLiang1** [Adyen/adyen-android#1562]
**Describe the bug**
the keyboard for Dropin compose hides fields and buttons as it doesnt push up the bottomsheet. The bottomsheet isnt scrollable as well

**To Reproduce**
1. Open drop in compose, and choose any option with a textfield in it

**Expected behavior**
Keyboard pushes up dropin bottomsheet

**Screenshots**
![image](https://github.com/Adyen/adyen-android/assets/83301551/2d2798ff-370a-4dbd-ab47-012882d1d12f)

**Smartphone (please complete the following information):**
 - Device: pixel 4, samsung galaxy s23+

**Additional context**

**Comment by OscarSpruit** [comment]
Hi @mikeLiang1, thank you for opening this issue! I was able to reproduce what you described, but I wonder if it is because compose handles focus and/or keyboards differently. In the attached video, you can see how the bottomsheet adjusts it's size based on which field is focused. Could you confirm if it works the same for you?

https://github.com/Adyen/adyen-android/assets/17701279/30b808fd-cb15-4121-b4cd-583b925b5907

**Comment by mikeLiang1** [comment]
Hey Oscar, thank you for the reply,
I can confirm that behaviour is the same, however would it be possible for the keyboard to completely push up the bottomsheet like how the non compose dropIn does? Or perhaps make the bottomsheet scrollable so that the keyboard wont cover the next button / save payment. We want to allow users to see these buttons even when the keyboard is up

**Comment by OscarSpruit** [comment]
@mikeLiang1 we found what is causing this. Could you try adding the line below in your XML theme? `AdyenCheckout.BottomSheetDialogTheme` has `android:windowSoftInputMode` set to `adjustResize`. This value causes the bottom sheet to adjust to the keyboard.

```XML
<item name="bottomSheetDialogTheme">@style/AdyenCheckout.BottomSheetDialogTheme</item>
```

**Comment by mikeLiang1** [comment]
Hey Oscar, it worked ! thank you very much for the help
