### ISSUE TITLE
Drop In Localization

### ISSUE THREAD

**Issue by nidhinprathap** [Adyen/adyen-android#163]
Even after passing the Locale to DropIn , The ui is not updating based on the provided Locale.
Tried Dutch, which is supported by Adyen.

> DropInConfiguration dropInConfiguration = new DropInConfiguration
>                 .Builder(mContext, resultActivity, ExtendedDropInService.class)
>                 .setEnvironment(Environment.TEST)
>                 .setShopperLocale(new Locale("nl-NL"))
>                 .addCardConfiguration(cardConfiguration)
>                 .build();

Even tried passing default Android locale for Chinese

> DropInConfiguration dropInConfiguration = new DropInConfiguration
>                 .Builder(mContext, resultActivity, ExtendedDropInService.class)
>                 .setEnvironment(Environment.TEST)
>                 .setShopperLocale(Locale.SIMPLIFIED_CHINESE)
>                 .addCardConfiguration(cardConfiguration)
>                 .build();

But Localization doesnt reflect on Drop In component. 

How to fix the Localization issue?

**Comment by caiofaustino** [comment]
As I mentioned in #157 the localization is not yet fully supported on our side.

You can add the missing localized strings by yourself, but it will use the device locale of the user for display. We will work on improving the localization to use the one passed on the `Configuration` object in the future as that was the initial plan, but is still WIP.

**Comment by arjenvanderende** [comment]
Dropping this here for others that run into issues with localization now that improved support is present.

Using the example code above should localize the UI and works for the example app provided in this repo. It did not work in our project however and would always fallback to the default English texts. It turned out that the Android Gradle Plugin was stripping the string resources needed for localization to work.

In `build.gradle` we had the following configuration:

```
android {
  defaultConfig {
    resConfigs "nl", "en"
  }
}
```

This needed to be changed to get the Dutch locale working:

```
android {
  defaultConfig {
    resConfigs "nl", "nl-rNL", "en"
  }
}
```

**Comment by caiofaustino** [comment]
@arjenvanderende thx a lot for that, super helpful, it seems counter intuitive, what the documentations says about that property is the exact opoosite o that, but this is indeed a nice optimization to have!
https://developer.android.com/studio/build/shrink-code#unused-alt-resources
