### ISSUE TITLE
Different Payment Options Available for iOS & Android

### ISSUE THREAD

**Issue by nidhinprathap** [Adyen/adyen-android#165]
I'm using Adyen Drop In across the iOS & Android. 
In iOS we are seeing a CVV field visible for user, but for Android the CVV field isn't visible. As per configuration the CVV shouldn't be visible in the app. Both are using same Configuration Key. But the Drop In component is showing different behaviour on Both the platforms.

Can i get a clarity why the platforms are showing different behaviour in Drop In Component for the same Configuration.

**Comment by caiofaustino** [comment]
hey @nidhinprathap,
Even thought we try to maintain compatibility and feature parity, the components on both platforms are developed independently. 
From what you said I assume the expected behavior for the configuration you passed would be to hide the CVV field, which is being done correctly on Android but not on iOS.
In that case, you can point that out to the iOS team in [this repository](https://github.com/Adyen/adyen-ios) and they can tell you if there is any difference or if this can be fixed soon.

Let me know if you have any more questions.
