### ISSUE TITLE
Amex number accepted when it's not allowed

### ISSUE THREAD

**Issue by ronaldvanduren** [Adyen/adyen-android#1705]
**Describe the bug**
I am using the credit card component and it's configured so it only accepts Visa and Mastercard. However, I have seen some logs in our back-end that indicate some users have tried to pay with American Express: `Internal Server Error: Could not find an acquirer account for the provided txvariant (amex)`. I can't reproduce it with the test card numbers from the Adyen Documentation, but I can reproduce it with other American Express testing card numbers. For example: `345678901234564`, so it seems to happen with Amex card numbers that start with `34`.  

**To Reproduce**
1. Enter an Amex card number like `345678901234564`.

**Expected behavior**
I would expect that the credit card number from Amex is not accepted, like the ones in the Adyen documentation. 

**Version of SDK**
5.6.0

**Comment by araratthehero** [comment]
Hi @ronaldvanduren, thanks for reporting this issue.

If the SDK does not recognize the card brand, we allow users to proceed with the payment. This might happen if the card brand detection fails. 
In the test environment, some test card brands are not being retrieved, which is a [known issue](https://github.com/Adyen/adyen-android/issues/523) we are addressing internally. This should not occur in the live environment.

Since this issue is not specific to the SDK, I would ask you to please [contact our support team](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) with the PSP references and the error details. They can help you further and investigate why the card brands are not being recognized.

**Comment by ronaldvanduren** [comment]
Hi @araratthehero, thanks for the elaborate answer. I will contact the support team!
