### ISSUE TITLE
The card component isn't removing the details that were previously added.

### ISSUE THREAD

**Issue by skamble01** [Adyen/adyen-android#1749]
Hi Team,

With the bottom sheet, I have one problem. When I try to pay with a stored card, the bottom sheet opens, and after that, if I close the bottom sheet without a payment and open it for another stored card, it displays the previously added details. when I wish to pay again and access the other card or saved card component. If i open the saved card and close the bottom sheet without payment, the card is not being cleared for other card details.

1. Open the saved card component.
2. Without making a payment, close it.
3. The bottom sheet gets closed (Saved card component).
4. Open it again for the other saved card payment.
5. When the bottom sheet is opened, it shows previously fetched or entered details.

Expected behavior
A clear card with the details previously entered.

The integration you're using : Component integration
The SDK version : 5.5.0

Thank you in advance for your help!
Sangram

**Comment by skamble01** [comment]
Any update on this team?

**Comment by skamble01** [comment]
Hi Team,
I am waiting for your reply as we are meeting deadlines.

**Comment by jreij** [comment]
Hi @skamble01, thanks for reaching out. As you have seen in the past few weeks, we have helped you with 6 different issues, all of which turned out to be integration questions. Even though Github issues should be primarily used for bug reports and feature requests, we are happy to assist you furthermore with your questions but please allow us the necessary time to answer. If you prefer you can reach out to our actual Support Team via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: [support@adyen.com](mailto:support@adyen.com) and they can help you more efficiently.

**Comment by jreij** [comment]
As for your current issue, we need more context to be able to assist you:
- Screen recording or screenshots of the scenario in question.
- All relevant code snippets including how you initialize and configure your component.
- The relevant information about the type of screens in which you are using the component.
- SDK logs. You can enable extensive logs by calling `com.adyen.checkout.core.AdyenLogger.setLogLevel(Log.VERBOSE)` in your application class and filter your logs by `CO.` to see the checkout logs only then share them here.

**Comment by skamble01** [comment]
Hi @jreij 
Thanks for your reply, and I'm happy that you guys are helping me. 

Please find below code snippets : 
1) For the configuration card component.
  val storedCardView = CardComponent.PROVIDER.get(
                fragment = this@BuyingPaymentDetails,
                storedPaymentMethod = storedPayment,
                checkoutConfiguration = checkoutConfigurationProvider.checkoutConfiguration,
                callback = this@BuyingPaymentDetails
            )
            setDialogToFullScreen(storedCardView)
2) Bottom sheet code 
   private fun setDialogToFullScreen(cardComponent: CardComponent) {
        bottomSheetDialog =
            BottomSheetDialog(requireContext(), R.style.AdyenCheckout_BottomSheetDialogTheme)
        adyenBottomsheetCardBinding =
            ActivityAdyenBottomsheetCardviewBinding.inflate(layoutInflater)

        bottomSheetDialog.onBackPressedDispatcher.addCallback(viewLifecycleOwner,
            object : OnBackPressedCallback(true) {
                override fun handleOnBackPressed() {
                    if (cardComponent.handleBackPress()) return
                    bottomSheetDialog.dismiss()
                }
            })
        bottomSheetDialog.setCancelable(true)
        bottomSheetDialog.setContentView(adyenBottomsheetCardBinding.root)
        bottomSheetDialog.setOnShowListener {
            val bottomSheetDialog = it as BottomSheetDialog
            val parentLayout =
                bottomSheetDialog.findViewById<View>(com.google.android.material.R.id.design_bottom_sheet)

            parentLayout?.let { it ->
                val behaviour = BottomSheetBehavior.from(it)

                val layoutParams = it.layoutParams
                layoutParams?.height = WindowManager.LayoutParams.MATCH_PARENT
                it.layoutParams = layoutParams

                behaviour.isFitToContents = false
                behaviour.halfExpandedRatio = 0.6f
                behaviour.state = BottomSheetBehavior.STATE_HALF_EXPANDED
            }
        }
        adyenBottomsheetCardBinding.cardView.attach(cardComponent, viewLifecycleOwner)

        bottomSheetDialog.show()
    }

    Screenshots of having issue
    1) When i open one saved card first time.
    
![Saved card Payment 1](https://github.com/user-attachments/assets/567f5fc3-c268-4811-8f8c-9398a88086e2)

2) after closing that bottom sheet for different card.

![Saved card Payment 2](https://github.com/user-attachments/assets/a98ab196-797a-42be-89f8-f2ebdc07a6ca)

If you find the selected option and open card details for the second time, then you will see a difference.


Let me know if you need any other details .

**Comment by jreij** [comment]
@skamble01 our components are tied to the lifecycle of the activity or fragment they are created in. Which means that they preserve their state until that activity or fragment is destroyed (to support screen rotation for example).

When creating your component you are attaching it to `BuyingPaymentDetails` which I suspect is the screen where all the stored cards are listed. This explains why you are seeing the same component after changing the card, because the fragment is still alive.

I can suggest 2 solutions:
- Since you are loading your component inside the bottom sheet it should be tied to that bottom sheet and not to the fragment before it. You can use a bottom sheet fragment instead and create the component inside that new fragment.
- You can use the `key` parameter in `CardComponent.PROVIDER.get(...)` to add a unique key to each component. This way you will have a different component instance for each stored card.

**Comment by skamble01** [comment]
Hi @jreij 
Thanks for the help. The first approach worked for me.
