### ISSUE TITLE
Demoserver Broken

### ISSUE THREAD

**Issue by ThinkBIG-Company** [Adyen/adyen-android#18]
The demo server can no longer be used.
Since yesterday I get a server error 500.

The URL that was used is right below:
https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/setup

Only for the Web-SDK it works properly !

**Comment by timon-langlotz** [comment]
Hi @ThinkBIG-Company,

Thank you for reporting this issue! As @joostvandijk has mentioned in adyen-ios, we're currently looking into it. As a workaround you can use our direct API (**only for testing purposes**). You can find the API key in the customer area. Please use `x-api-key` instead of `x-demo-server-api-key` in the HTTP request header.

Cheers,
Timon

**Comment by emredincer** [comment]
Demo server is up and running again.
