### ISSUE TITLE
Update 4.13.x to use adyen-3ds2-android 2.2.21

### ISSUE THREAD

**Issue by BenedictP** [Adyen/adyen-android#1854]
## Description
Wanted to ask if you plan to release a new version with the latest 3DS2 dependency? We got this information: https://help.adyen.com/updates/update-to-adyens-3ds2-android-sdk-for-android-15 and we are still using a 4.X.X version so we can not easily migrate to a 5.X.X version.

## Code Snippets (if applicable)
Provide any relevant code snippets that illustrate your question or the problem you're experiencing.

```
Insert your code here
```

## Integration Information
1. Server-side integration: Sessions/Advanced flow
2. Client-side integration: Drop-in/Components
3. SDK version:

## Additional Information
Include any other details that might help us understand your question better. This could include links to documentation, related GitHub issues, or any steps you've already tried.

**Comment by araratthehero** [comment]
Hi @BenedictP, thank you for your question regarding potential Android 15 issues with our SDK.

We updated [the message](https://help.adyen.com/updates/update-to-adyens-3ds2-android-sdk-for-android-15) yesterday to clarify the impact based on your setup. The changes apply if you want your app to target Android 15 (API 35). Currently, the SDK won't function only on new devices with a 16KB page size—none of which are on the market yet. On other devices, there might be a minor UI glitch in the native 3DS2 flow.

Please review the update if you haven’t already, and reach us again if you still have questions. At this time, we don’t plan to update SDK version v4.X.X due to the minimal impact.
