### ISSUE TITLE
How to dismiss BottomSheetFragment?

### ISSUE THREAD

**Issue by alvin96** [Adyen/adyen-android#197]
Hi all,

May I have the code snippet or default Adyen function to dismiss `BottomSheetFragment` of credit card details?

**Comment by caiofaustino** [comment]
Hi, for the Drop-in there is currently no way to dismiss the bottom sheet, what is the use case you plan for this?

**Comment by caiofaustino** [comment]
Sorry that's not possible on the Drop-in. If you want to implement something like that you can use the Components instead, it's a little more work to implement but it gives you more control and flexibility.

**Comment by alvin96** [comment]
Will this support in the future? Because iOS have this feature `self.dropInComponent.viewController.dismiss(animated: true, completion: nil)`

**Comment by caiofaustino** [comment]
Not that I'm aware, we don't have that planned for Android because the mechanism to display things is really different.  But I'll discuss with the team.

**Comment by caiofaustino** [comment]
Also for your use case, there is no way to you to get the card type in real time on the Drop-in, so you wouldn't even be able to know if the cars is not supported until the shopper clicks pay.

**Comment by alvin96** [comment]
Okay, I will try with the Components. Thank for your response.

**Comment by Kalzeroth** [comment]
This was clearly a [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem), but I think the question being put in foreground should still be answered => Dismissing a popup/window/sheet or whatever shown through a library should be a given IMHO.

**Comment by caiofaustino** [comment]
Thx for the consideration @Kalzeroth, I believe that what you want to achieve as well is to cancel the payment flow in that case right? Also why do you want to do that?

There are scenarios where the payment might be redirected to another app and your app might be put into the background, I think that would break the payment flow.

**Comment by Kalzeroth** [comment]
I didn't consider the payments redirections but I still think it could be useful to cancel it altogether in some edge cases. (say you have infos from another source than the user itself that the payment isn't needed anymore)


My case is a little weird and as you pointed out I can't really cancel the Drop-in totally since I can't check if the onResume is called from a redirection or just the app being bought back to front. `(Which would be nice for other reasons too, but I think I have seen some other response you have wrote saying it's not possible)` 

The core problem is some graphical issues with the activity behind the bottomSheet flashing black ONLY after the app was put in background and comes back to foreground. If you are interested, I have a QRcode scanner / Camera (`com.budiyev.android.codescanner.CodeScannerView`) behind, but with the preview stopped.

I am currently considering about opening a ticket about this since I didn't find any other similar issue, but lacks the time to check if it is connected to the QRcode scanner library or your awesome Drop-in 👍

**Comment by caiofaustino** [comment]
Thanks for calling it awesome :)

Yeah I assume it's probably related to that camera preview since those have a more complex display logic. If the issue is just visual I'd suggest adding an intermediate screen after the QR code scan is successful to be the one actually showing behind the Drop-in. But let us know if you find anything else.
