### ISSUE TITLE
Google Pay make payment token is json object and not string

### ISSUE THREAD

**Issue by andre-sonect** [Adyen/adyen-android#330]
According to documentation the google pay token is a string but is coming as a json object.

**Expected behavior**
Expecting a string token

**Smartphone (please complete the following information):**
 - Nexus 5X
 - Android 8.1
 - Drop-in version 3.8.0

`"paymentMethod":{"googlePayToken":"{\"signature\":\"MEQCIHMRpeg7FKf7u0pyUL6emb2krEJsqlbDR25ogBsjqeRCAiBL2RL3a8QxUJNhNoQ6+uJclxy32k8qGNtMoytm4zSvNQ\\u003d\\u003d\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"50CT1wY0hU5sQSAd2Y9Q4Vy24PbBAHBJlDr4XwP/7M1DUo2uf7mue4Kp8Q5JK1tD5JUp0Pe/hAyimP+SfXCknpCTLEs6swRhnzKIHYRGKm/YPisCNfUVGoN/P8zwKtwjoWIsi3nShROUveF2A4QjlRcOyqA/zqiswiAuJxJoHOkVXirP5RVy6pj8gJRjAFIEWBTFpjlktC13uxo1tOrUT2h+2OGQKXJm+gYpT6T2b7iS3howNwDYdFt+ou00SYxq4vs0A3qlSX7YTv2qsJtD/nxKJNLM5kOm57lGJ57iGbUwoh+3kmoGaBHsp+TTv0aq0U66fMHk6Oj8bXxBkzKns9txs5KfUm4L5kkvWAOoTFBia9Q5r7lHK5scEYGrNLV2O0lWhnuSYykvmaF9zMJsXjoc9YYFhEN2MlC1PSePos4ANKnqgcrBKY6Fox5qvW2RCdZPySOQnMBz8thdfASolDahPg\\\\u003d\\\\u003d\\\",\\\"ephemeralPublicKey\\\":\\\"BAr0PKlySyEPwr2UeMCvnI75Ut8OjjvVGRamd4OvQjoOKxb2RhIv4/XR0ksTY9Piv/lBIe7C4svC9aItT50Mg4I\\\\u003d\\\",\\\"tag\\\":\\\"zGVUx7fHtDYymakmGZ9PVDh6f1ELXqkw5C7kQ6/mSZg\\\\u003d\\\"}\"}","type":"paywithgoogle"}`

**Comment by guillermomuntaner** [comment]
This is hitting us too (in our case due to Paypal). The issue seems related with updating our servers to Checkout API v64. In particular, the problem seems to come from:
 here https://docs.adyen.com/online-payments/release-notes#changes-4
> Changes
> POST /paymentMethods
> The response for Amazon Pay, Google Pay, PayPal, and Korean cards now contains a configuration object. Example for Google Pay

The iOS SDK seems to handle this well, but on Android even the most up to date SDK is throwing the error because of this.

Is there any way to fix this up? Are we missing something here?

This seems a major issue between your endpoint updates & SDK update and I couldn't find any info about this issue anywhere else.

The exception during deserialization:
`UnknownError(e=com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 446 path $.paymentMethods[2].configuration, request=Request{method=POST, url=[refacted]/adyen/payment/methods, tags={class retrofit2.Invocation=[redacted].postAdyenPaymentMethods() [79285, [redacted].network.requests.AdyenPaymentMethodsRequest@1b12255]}})`

**Comment by caiofaustino** [comment]
Hey there, sorry but these seem to be different issues. 

@guillermomuntaner , I already replied to you on the support ticket, we will release a quick fix for this, but you can also remove the `configuration` object from the API response before parsing it to the SDK as it's not yet used internally.

@andre-sonect , this doesn't seem to happen in our tests. Perhaps can you take a look at your `DropInService` implementation and maybe log the response like  `paymentComponentData.toString(4)` just to make sure?
You can check here our model object receives and parses the parameter as a String.
https://github.com/Adyen/adyen-android/blob/3.8.0/base-v3/src/main/java/com/adyen/checkout/base/model/payments/request/GooglePayPaymentMethod.java#L66

**Comment by andre-sonect** [comment]
Hi @caiofaustino I had a support ticket that responded that the data I got is correct since it is a json object that got converted to string.

**Comment by caiofaustino** [comment]
yeah, the data is correct, the content of the token string is a JSON object, but it's typed as a String.
So it should be `"paymentMethod":"{"goo...` instead of `"paymentMethod":{"goo`
