### ISSUE TITLE
Credit Card Scan

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#34]
Was the option for Credit Card Scan removed in version 2?

**Comment by timon-langlotz** [comment]
Hi @georgij,

since this feature was not really used and required external libraries, we've removed it. We've however added a module which you can opt in for to have a credit card reader with the NFC chip of the device. In the quick integration, you can just add `implementation "com.adyen.checkout:nfc:${checkoutVersion}"` to integrate. I do need to mention though that this feature requires a contactless card, and scanning results also depend on the quality of the card's and phone's NFC chip.

Cheers,
Timon

**Comment by georgij** [comment]
Ah, OK.

**Comment by SirVer** [comment]
@timon-langlotz Sorry to necromance this old issue: Having a visual credit card scanner would be an interesting feature for Qwello. Is it possible for us to build this feature ourselve and hook it into adyen-android somehow?

**Comment by caiofaustino** [comment]
hey @SirVer, unfortunately this is a bit complicated. I assume you are on one of our 3.x.x versions. So as I see it you can either:
- Rely on Google's built in functionalities to scan a card
- Use a 3rd party library and encrypt the card data using our CSE module to make the API call

but on unfortunately there is currently no way to hook the response of a card scanning feature directly into the Drop-in or Component.

**Comment by SirVer** [comment]
Thanks for your feedback!

> Use a 3rd party library and encrypt the card data using our CSE module to make the API call

That sounds like a path to go. Is that documented somewhere? Will I need to deal with 3DS myself for example?

**Comment by caiofaustino** [comment]
I'm not sure, but I don't think that's documented. You can still use the Redirect and 3DS2 Components to handle the API response.

**Comment by SirVer** [comment]
I'd love to see some code examples of that. I assume there are none around, right?

Thanks again for all your help.
