### ISSUE TITLE
Redirect back to app doesn't work if it was started from another app (Gmail, WhatsApp)

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#369]
To reproduce, an app using the Adyen SDK is needed that can be started using a web-link:

- Create an email in the Gmail app with a link that will open the app, and click the link
- Gmail will now open the app with an `Intent` that has `FLAG_ACTIVITY_NEW_DOCUMENT` set
- Start an Adyen payment flow in the app, with a payment method that leaves the app (for example iDEAL)
- Complete the payment

Expected result:
- The user is redirected back to the app

Actual result:
- The Adyen SDK shows a popup saying: "There was an error while processing your payment. Please try again later."

Tested with Adyen Drop-in SDK 3.7.3 and 3.8.2.

So there are really two problems here. Obviously the fact that the redirect is not working is one, although I can hardly blame Adyen for this, because who knows what is going on with Android intents and all the different flags.

But secondly the error message is problematic. Because in fact the payment did complete, so the user has already paid. The error message encourages the user to make another payment.

(For the `FLAG_ACTIVITY_NEW_DOCUMENT` problem I have already added a workaround to our app. When I detect this flag, I simply relaunch our launcher Activity without the flag.)

**Comment by geertjan-tiqets** [comment]
I just found out the `FLAG_ACTIVITY_NEW_DOCUMENT` is not the only thing that can cause this problem.

Other apps like WhatsApp don't actually set this flag when you open an app by clicking on a link, but the same error appears from the Adyen SDK. I found out in this case, the problem is a missing `FLAG_ACTIVITY_NEW_TASK` task. I updated my workaround to check for this too.

I will update the title of this issue to reflect this.

**Comment by jreij** [comment]
Hi @geertjan-tiqets, thank you for your feedback and the detailed explanation! I investigated this issue thoroughly and it is indeed frustrating.

To explain a bit what I think is happening:
* When you call `DropIn.startPayment` we launch a `DropInActivity` using `startActivityForResult` to handle the drop in there.
* After a redirect has completed, we use deep linking in order to go back to the same activity and handle the result of that redirect. To make sure this deep link reaches the same activity that was already open, we set its launch mode as `singleTask`.
* When your app is launched from an external app, it's launched under the same task of that app, meaning your activity is added to that application's stack.

This somehow breaks our redirect: instead of going back to the same `DropInActivity`, the system is creating a new activity under a new task, this new activity is not initialized properly and does not know of any redirect in progress, which is why you see this error message. The combination of the points above is unique and if we can change any of them the issue would not happen. But unfortunately we cannot remove neither `startActivityForResult` nor `singleTask` as they are fundamental parts of how the SDK functions.

However, if you can set the launch mode of your activity (the one calling `DropIn.startPayment`) to `singleTask` or `singleInstance`, the system will redirect back to the correct task and the payment would succeed. The other way, I guess, would be the workaround you are using now.

Let me know if you have a better understanding of this or if you can think of a better solution, I'd be happy to try it.

**Comment by geertjan-tiqets** [comment]
Hi, sorry for the late reply, I finally had time to look into this. :smile: 

Indeed, using `singleTask` on our launcher activity works! It has the same effect as my workaround of manually relaunching the activity for certain flags, but it's a cleaner, more proper solution.

Thanks for the help!
