### ISSUE TITLE
Crash on 3DS2 Challenge

### ISSUE THREAD

**Issue by Arthur-Tavais-Turbi** [Adyen/adyen-android#407]
Hello.

I am using the version 3.8.0 of the SDK and i am having trouble do make the 3DS2 challenge. The challenge Activity appears, the user make the challenge, but it crashs on the return and i receive this error:

"Failed to make challenge, missing reference to initial transaction."

![image](https://user-images.githubusercontent.com/61332045/121018031-54562e80-c774-11eb-8175-f88514454f2e.png)

Am i missing somenthing?

**Comment by jreij** [comment]
Hi, are you using drop in or the standalone components? And can you provide some logs from before and after launching the 3DS2 challenge?

**Comment by Arthur-Tavais-Turbi** [comment]
I am using the Adyen3DS2Component. It shows the challenge to the user, the user makes the challenge, but it triggers the .observeErrors with an Authentication3DS2Exception message and the log above.  Here are some print of the code while debuging it:

Here i Itinialize the component, get the parameters i need and then i call the API on our side:
![Captura de Tela 2021-06-08 às 15 38 11](https://user-images.githubusercontent.com/61332045/121239424-99ab5680-c86f-11eb-8eab-66a2c90808b7.png)

After the API responds, i show de challenge screen, do it and then it returns in this observe again:
![Captura de Tela 2021-06-08 às 15 51 46](https://user-images.githubusercontent.com/61332045/121241198-8ef1c100-c871-11eb-9534-cef4739e20e3.png)

And in sequence it trigs the observeError on the component with the message error :
![Captura de Tela 2021-06-08 às 15 53 35](https://user-images.githubusercontent.com/61332045/121241592-ff004700-c871-11eb-8120-4c30df6cd2ba.png)

It appears to suceed the challenge, but it triggers this authError in sequence anyway. Should i ignore it?

**Comment by jreij** [comment]
Thanks for providing more info. Can you provide some logs also? Maybe set the log level to verbose using `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)` in your application class, and filter logs by `Adyen3DS2Component`. It should tell us more about what's happening.

My initial assumption based on the `"Failed to make challenge, missing reference to initial transaction."` error message, is that you are not using the same instance of the `Adyen3DS2Component` to handle both the fingerprint and the challenge actions. The same instance that handled the fingerprint action should also handle the challenge action, because it needs to keep a reference to the initial 3DS2 transaction, otherwise you get the `"missing reference to initial transaction"` error.

**Comment by misterjunio** [comment]
@jreij I'm facing a similar issue. Looking at your [test cards documentation](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication), I'm trying to cover the following scenario:

<p style="box-sizing: border-box; margin: 8px 0px; overflow-wrap: break-word; color: rgb(0, 17, 44); font-family: fakt, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, roboto, oxygen, ubuntu, cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">To test the web-based flow where the device fingerprinting step is skipped (because the issuer's ACS has not configured a<span> </span><code style="box-sizing: border-box; font-family: menlo, consolas, &quot;Andale Mono WT&quot;, &quot;Andale Mono&quot;, &quot;Lucida Console&quot;, &quot;Lucida Sans Typewriter&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Liberation Mono&quot;, &quot;Nimbus Mono L&quot;, monaco, &quot;Courier New&quot;, courier, monospace; font-size: 14px; border-radius: 4px; background-color: rgb(243, 246, 249); display: inline-block; line-height: 25px; padding: 0px 6px; min-height: 24px; color: rgb(0, 17, 44); max-width: 100%;">threeDSMethodURL</code>), and you get a<span> </span><strong style="box-sizing: border-box; font-weight: 600;">ChallengeShopper</strong><span> </span><code style="box-sizing: border-box; font-family: menlo, consolas, &quot;Andale Mono WT&quot;, &quot;Andale Mono&quot;, &quot;Lucida Console&quot;, &quot;Lucida Sans Typewriter&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Liberation Mono&quot;, &quot;Nimbus Mono L&quot;, monaco, &quot;Courier New&quot;, courier, monospace; font-size: 14px; border-radius: 4px; background-color: rgb(243, 246, 249); display: inline-block; line-height: 25px; padding: 0px 6px; min-height: 24px; color: rgb(0, 17, 44); max-width: 100%;">resultCode</code><span> </span><em style="box-sizing: border-box; font-family: fakt, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, roboto, oxygen, ubuntu, cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: italic;">immediately</em><span> </span>after submitting the payment request, use the following card:</p>

Card Type | Card Number | Expiry Date | Security Code (CVC/CVV/CID)
-- | -- | -- | --
Visa | 4212 3456 7891 0006 | 03/2030 | 737

It seems like the SDK doesn't handle this at all, as it always requires an `IdentifyChallenge` result before a `ChallengeShopper` one. It might be my misunderstanding of the above docs, which do state this card is to "test the **web-based** flow". However, how can I guarantee that my mobile app user will not use a card that triggers this flow?

**Comment by jreij** [comment]
Hi again, are you still experiencing any issues with this?

**Comment by misterjunio** [comment]
I have long since left that project, so I don't know if any real issues came out of it or not
