### ISSUE TITLE
V 3.8.3 still requires jCenter repository, even after made available in mavenCentral

### ISSUE THREAD

**Issue by Vkalns** [Adyen/adyen-android#423]
**Describe the bug**
Updating to V 3.8.3 still requires `jCenter()` repository due to embedded dependencies

**To Reproduce**
1. I updated our   `com.adyen.checkout:drop-in:` dependency to v 3.8.3
2. I removed `jCenter()` from repositories list
3. I tried to build the project
4. I see the error that Android Studio can't find two dependencies `Could not find com.tencent.mm.opensdk:wechat-sdk-android-without-mta:5.1.6.` and `Could not find io.michaelrocks:paranoid-core:0.3.2.`
 
**Expected behavior**
The latest stable version of `adyen-drop-in` should be available in mavenCentral and all the dependencies it requires would also be available so that the project would build successfully

**Additional context**
I understand that there was an [issue](https://github.com/Adyen/adyen-android/issues/337) closed about `io.michaelrocks:paranoid-core:0.3.2.` not being available in mavenCentral.  Thought this doesn't solve the issue, as the fix is only available in the beta and in V4.x. Also I could argue that the changelog message for `V 3.8.3` is a bit misleading, as it still depends on `jCenter` repository

**Comment by caiofaustino** [comment]
Unfortunately we can't change the transitive dependencies of releases that already exist. Newer versions don't depend on `io.michaelrocks:paranoid-core:0.3.2` anymore, and updating the 3DS2 version on `3.8.4`for example would have other consequences for the 3DS2 authentication flow which I thought would be better kept for the new versions only.

I recommend commenting about this on the original library request so that he can publish his older lib version on Maven Central as well.
https://github.com/MichaelRocks/paranoid/issues/45#issuecomment-819546024

**Comment by caiofaustino** [comment]
Also alternatively you can download that dependency and add it to a local maven repo in your build environment so that you still have it available after JCenter shuts down.

**Comment by caiofaustino** [comment]
Since this is not in our power I'm closing this issue. We recommend that you update to the latest version to fix this.

**Comment by caiofaustino** [comment]
Since this is not in our power I'm closing this issue. We recommend that you update to the latest version to fix this.
