### ISSUE TITLE
PaymentComponentData in DropInService 

### ISSUE THREAD

**Issue by leonlee0116jl** [Adyen/adyen-android#428]
Hi, I have extended `DropInService`. I wonder is there any way to get credit card brand (eg. "mc") from the `paymentMethod` of `jsonObject` in `makePaymentsCall` ?

Right now I only able to get `type` `storedPaymentMethodId ` and `encryptedSecurityCode ` only.

Thanks

**Comment by jreij** [comment]
Hey, which version of the SDK are you using? This is not supported in v3 but it is in v4. You can check out the `checkPaymentState` method in the `ExampleAsyncDropInService`. Beware that the implementation is a bit different from the current one you have because you will need to override `onPaymentsCallRequested` instead of `makePaymentsCall` and you need to manage the threads yourself but hopefully the example will make it easier.

We have already made a few alpha and beta v4 releases and we will release the stable version very soon (today or tomorrow).

**Comment by leonlee0116jl** [comment]
> Hey, which version of the SDK are you using? This is not supported in v3 but it is in v4. You can check out the `checkPaymentState` method in the `ExampleAsyncDropInService`. Beware that the implementation is a bit different from the current one you have because you will need to override `onPaymentsCallRequested` instead of `makePaymentsCall` and you need to manage the threads yourself but hopefully the example will make it easier.
> 
> We have already made a few alpha and beta v4 releases and we will release the stable version very soon (today or tomorrow).

Thanks for the fast response! I will look into v4 beta.
Will we get migration guide to v4 for DropInService when stable version release?

**Comment by jreij** [comment]
Yep but not right away, the migration guide is still a work in progress!

**Comment by jreij** [comment]
@leonlee0116jl 4.0.0 is live now :)

**Comment by jreij** [comment]
@leonlee0116jl the [migration guide](https://docs.adyen.com/online-payments/android/migrate-to-android-4-0-0) is here!

**Comment by sherzodnosirov** [comment]
> @leonlee0116jl the [migration guide](https://docs.adyen.com/online-payments/android/migrate-to-android-4-0-0) is here!

Hi! unfortunately this link redirects me to the "Build your integration" page, instead of the migration page. Is there any way to see the migratio guide from the version 3 to 4?
