### ISSUE TITLE
Disable Sepa direct debit

### ISSUE THREAD

**Issue by FabioCappelliSpot** [Adyen/adyen-android#44]
Hi,
How can I disable "**sepa direct debit**" choice when start CheckoutActivity without implements custom integrations?

I see in latest version there is a field _blockedPaymentMethods = ['sepadirectdebit']_ to achieve it but I use api version v32.
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/paymentSession

Thanks

Fabio

**Comment by timon-langlotz** [comment]
Hi Fabio,

sorry for not getting back to you earlier. I had seen your issue, but it looks like there was some GitHub hickup, since the issue was gone a couple minutes later. Therefore I thought you had closed it!

Would you like to generally disable Sepa Direct Debit as a payment method, or just for certain shoppers? If you want to disable it completely or enable it based on regional or amount restrictions, you can contact our [Support](support@adyen.com).

Hope this is still helpful for you!
Cheers,
Timon

**Comment by FabioCappelliSpot** [comment]
Hi, I created the same issue more times because github seemed to delete it.

I resolved the question check #36 

Thanks!
