### ISSUE TITLE
didOpenExternalApplication equivalent for Android SDK?

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-android#578]
Let me first explain why we use `didOpenExternalApplication` in the iOS SDK.
We noticed that users often run into this problem:

1. Choose Payconiq as payment method, resulting in a /payments call and subsequently opening the Payconiq app. 
2. Quit the Payconiq app without completing the payment
3. Open up our app again, which is still showing the dropin
4. Pick a different payment method, which results in a new /payments call
5. Our backend blocks the second /payments call to prevent double payments from occuring.

Now, for iOS there is this function `didOpenExternalApplication` that we can hook into. We built a mechanism that automatically closes the dropin in this case:

We detect on the JS side (our app is react native) that we came back from background and call a custom function on the native side, which checks if the Adyen dropin has both opened an external application and has *not* handled a response from activityresult, and closes the dropin in that case. 

Is there a way to implement this behaviour on Android? Another idea I had was to allow a second /payments call if the first one was type bcmc_mobile. Would this work?

**Comment by caiofaustino** [comment]
Hey there,
This is a bit of a common issue with asynchronous payment methods, and indeed it should be up to you to decide which approach you prefer.
We don't currently have any feedback about the Drop-in being resumed after a redirect. Could be an interesting information for you to take action indeed. We will discuss this internally, thanks for reaching out.

**Comment by jreij** [comment]
Hi @xanderdeseyn, as part of our upcoming major release (5.0.0), we added a callback that will trigger when a redirect is made outside of the app. It's called `setOnRedirectListener` for components and `onRedirect` for drop-in.

This will not cover 100% of the use cases, like for example when a payment method that uses its own SDK switches to an external app through that SDK (since we don't have visibility over that). But for most use cases this callback will be triggered.

This feature is set to be released in the next few weeks, through the first beta release of v5.

**Comment by jreij** [comment]
Hi again, we just released [5.0.0-beta01](https://github.com/Adyen/adyen-android/releases/tag/5.0.0-beta01) with the feature mentioned above. Feel free to pick it up and send us your feedback!
