### ISSUE TITLE
IdealComponent's observer triggered immediately after attaching the issuers with Spinner view

### ISSUE THREAD

**Issue by ranjith-thandayuthapani** [Adyen/adyen-android#779]
I am integrating IDealComponet. while setting up the spinner after i get the Issuers list, the observer triggered immediately.

`IdealComponent component = IdealComponent.PROVIDER.get(this, paymentMethod, configuration);
			idealSpinnerView.attach(component, this);`
                 
`component.observe(this, new Observer<GenericComponentState<IdealPaymentMethod>>() {
				@Override
				public void onChanged(GenericComponentState<IdealPaymentMethod> idealPaymentMethodGenericComponentState) {
				}
			});`

Tried by putting the attach before observing and after observing.

 Also if we close the Redirect webview and and come back to the same page the next time when i invoke the ideal spinner, Observer is triggered with previously selected option.  As it is using the lifecycle and saved state. any way to reset those states when the webview closed?

My codebase is in JAVA and following MVP architecture.

**Comment by jreij** [comment]
Hi, thanks for reaching out. When using the spinner, the first item is loaded by default which means the `observe` method will be triggered indeed because there is an item selected. The spinner was designed with the idea that you need to add a button to the screen and the user has to click the button to proceed.
