### ISSUE TITLE
How to get google pay payment method

### ISSUE THREAD

**Issue by wanderwuuu** [Adyen/adyen-android#79]
![4DC67831866D9CD66C2D404C364B3D21](https://user-images.githubusercontent.com/18542962/59980510-90e0fc00-9629-11e9-8ae0-2225b508a042.jpg)
Google pay is not in the list, how should I get it?

**Comment by carstenhag** [comment]
I am wondering about this too! Is there an example for Google Pay with the new Drop-in sdk?

**Comment by caiofaustino** [comment]
Sorry for the delay.

@wanderwuuu you need to add the GooglePay module dependency to your project
`implementation "com.adyen.checkout:googlepay:$versions.checkout_sdk"`

@carstenhag So on the new Drop-in we haven't implemented Google Pay yet. Since this is a completely new integration we will be continuously improving it, Google Pay is on the top of our priority list so it shouldn't take too long. 
Are you already experimenting with the new version? We are looking for any feedback :)

**Comment by carstenhag** [comment]
I am currently writing my bachelor thesis and trying to develop a prototype with Google Pay :)

Doesn't matter if I use the old one or the new one, but I haven't figured out how it works yet.
