### ISSUE TITLE
Card type detection from card number

### ISSUE THREAD

**Issue by Matej-Hlatky** [Adyen/adyen-android#81]
Hello,

For **credit card type estimation from entered card number** in Android we are using this code:
```kt
paymentMethods.filter {
    com.adyen.checkout.core.card.CardType.forTxVariantProvider(it)?.isEstimateFor(cardNumber) == true
}
```
Used dependency: `com.adyen.checkout:core-card:2.4.5`

When entered "4", this matches `visa`, `maestro` and `mc`.
According to various sources, _4..._ cards are only **VISA** or co-branded Dankort (`visadankort`) cards.

Also official [adyen.js](https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/2.5.0/adyen.js) uses different regular expressions to match card type and for _4..._ it is only `cartebancaire`, `visaalphabankbonus` and `visa`.

It would be great, if these rules will reflect valid rules and will be united in all SDKs (JS, Android, iOS).
Thank you

**Comment by caiofaustino** [comment]
Hey,

So I checked with the web team about the adyen.js check and they indeed seem to differ a bit from Android. They said they will be looking into this, I'll also check with iOS.

That said, please keep in mind that this is always just an estimation. The BIN ranges are dynamic and have overlaps that might not seem intuitive to various sources. We use these only as a visual aid for the shoppers, but the actual valid brand recognition only happens when the payment is made and goes through the back-end, as it also depends on the specific configurations of each merchant.

We might in the future look into different solutions on brand recognition, but for now this is the best we can provide.

**Comment by Matej-Hlatky** [comment]
Hello @caiofaustino ,
Thank you for reply.

Just to let other devs know, we have resolved this issue by porting iOS Swift code into Kotlin.
iOS code rules looks quite similar to JS.
