### ISSUE TITLE
Receiving results from Adyen3DS2Component with destroyed Activities

### ISSUE THREAD

**Issue by saxophone** [Adyen/adyen-android#93]
We are going to use the [3D Secure 2 Components](https://docs.adyen.com/checkout/android/components#3ds2-component) SDK  to handle 3ds2 verification in our own checkout UI. When I enable the "Don't Keep Activities" developer option and attempt a checkout that goes through the 3ds Challenge flow (which opens another Activity), the observers I set on `Adyen3DS2Component` are not invoked when I complete the challenge. This results in the user not being able to make a purchase since I can't submit the challenge result to our own servers since my code never received it.

I believe this is because my observers are removed from the backing `LiveData` when the `LifecycleOwner` I use to observe the results + errors, which is an Activity, moves to the `DESTROYED` state. Activities that are in the background can be destroyed at any time by the OS, especially for low-memory devices, so this is a case that I expect to happen when we go live.

What should I do to receive Challenge results when the lifecycle I'm using to observe the results gets destroyed?

**Comment by caiofaustino** [comment]
Hey @saxophone, 

So the problem here is a bit tricky. The 3DS2 SDK needs to comply with the specs from EMVCo on how the initialization and flow happens. And so when we initialize 3DS2 we get a `Transaction` object that needs to be used to continue the authentication. 

We are currently storing that object in the `Adyen3DS2Component` which is a `ViewModel` so it will outlive configuration changes, but not Activity destroy like you mentioned. But the transaction object is not something we can save on a `Bundle` or somewhere to recreate later.
The only alternative I see is putting the `Transaction` on a static object, but if the OS decides to kill the process to free up memory it will still lose the reference to that object and fail the Authentication flow anyway.

So from my perspective, this is a problem of EMVCo specifications not being so concerned with Android lifecycle problems. And in a real life scenario, I don't expect the OS to kill the Activity of the app that is in foreground that often, but if it does go to the background and is killed, I think the only solution is to show and error and start the Authentication flow again.

We can try to identify in the `Adyen3DS2Component` if the component was restarted and the reference was lost to throw and error on the `observeErrors()` in order to help make this issue more clear.

If you have any other ideas on how we can work around this I'd love to hear your thoughts.

**Comment by saxophone** [comment]
Hi @caiofaustino, thanks  for the detailed answer. Unfortunately I don't have any great ideas for how to work around this. I can step around the problem by keeping a static reference to the `Adyen3DS2Component`, but doing so with a `ViewModel` is an anti-pattern and so it's not viable. 

I suppose if your SDK launched a Fragment that contains the necessary Challenge steps _instead_ of an Activity, `Adyen3DS2Component` could be a `SharedViewModel` initialized with our Activity, and therefore would persist through the Challenge flow, no matter what. However this would likely make the API to your SDK much more cumbersome, which I recognize would be a difficult tradeoff to make. As it is now, the Component SDK is very easy to use, so thank you for that.

Throwing an error on `observeErrors()` if the reference is lost is a good idea and would make our users' experience better in case this happens to them. This would let us avoid writing logic to save state in the Activity that we're processing a Challenge and show the use an error message if the Activity is destroyed during the challenge. The checkout flow is the absolute last place we want to confuse customers, so your SDK responding with errors would be very helpful. Thanks!

**Comment by caiofaustino** [comment]
I'm glad you find the Components easy to use, that was our main goal.

I will work on trying to pin point the error and throw an update on the `observeErrors()` on a future release.

But I think this scenario is highly unlikely to happen in a real use case. We will try to get more data/insights from people using it when it goes live.

Feel free to provide any more feedback an open other issues when necessary.
Cheers.

**Comment by rrocav3** [comment]
Is this solved? Cause I'm getting different references with Destroyed Activities so the callback is not being received...
