### ISSUE TITLE
ResultCode.java is removed

### ISSUE THREAD

**Issue by VladimirWrites** [Adyen/adyen-android#94]
What is the reason behind the removal of `ResultCode.java` in the version `3.1.0`?
It was really useful to have result codes on the library side.

**Comment by caiofaustino** [comment]
Hi Vladimir,

What was your use case for the ResultCode? We were not using the class anymore since after a change on the API response we only need to look into the `action` object of the response to figure out if there is additional actions required on the app or not. Otherwise I guess the ResultCode could be useful just as a documentation source, but it might not be up to date all the time.

Let me know and maybe we can add it back in the next release if you think it's worth it.

**Comment by caiofaustino** [comment]
FYI
https://docs.adyen.com/checkout/payment-result-codes

**Comment by VladimirWrites** [comment]
I am using it to differentiate 3DS1 (redirect) and 3DS2 `Action` because it's handled by different components and it's the same object.

**Comment by caiofaustino** [comment]
The `Action` object is a base for the specific ones. Depending on the `type` content it will be parsed to either an`RedirectAction` ,`Threeds2ChallengeAction`, `Threeds2FingerprintAction`, etc...

Maybe I should create a similar helper with the possible Action types, since it's probably easier to read than having to look into the ResultCode. You can also use the `canHandleAction()` method on any `ActionComponent` to see if that component can handle that specific action type.

**Comment by VladimirWrites** [comment]
Thanks for the clarification! 
I didn't know about `canHandleAction` method. It would be really helpful to have it mentioned somewhere. The helper would also be nice. 
Thank you for the super fast support.
