### ISSUE TITLE
Redirect configuration icon not loading

### ISSUE THREAD

**Issue by jennyvbrown** [Adyen/adyen-android#955]
We are loading our own custom bank account form using the redirect configuration for Android. When the payment list loads, the icon for bank account does not load. The error in logcat is: 
Execution failed for logo  - https://checkoutshopper-test.adyen.com/checkoutshopper/images/logos/small/RedirectConfiguration-xxhdpi.png

The redirect configuration we are passing into our dropin component is this:

    val redirectConfiguration = RedirectConfiguration.Builder(context, ADYEN_KEY_TEST)
                .setEnvironment(Environment.TEST)
                .build()

We build our list of payment methods using this:

val ba = PaymentMethod()
            ba.type = "RedirectConfiguration"
            ba.name = "Bank Account"

**Comment by jennyvbrown** [comment]
![Screen Shot 2022-12-09 at 9 37 26 AM](https://user-images.githubusercontent.com/31461054/206749175-14f2f9b1-5ce3-4235-bd05-6d8538dbb892.png)

**Comment by ozgur00** [comment]
Hi @jennyvbrown! Thanks for bringing the issue to our attention. 

I see here you're constructing a `PaymentMethod` object manually and since you're passing `RedirectConfiguration` as `type` parameter you're forming the logo url that fails. This call fails because the type `RedirectConfiguration` isn't a valid type. 

Our `PaymentMethod` object shouldn't be created manually. Instead, you should pass the response that you received from `/paymentMethods` endpoint. 

Can you provide me with more information regarding the Bank Account payment method and why was it necessary to pass this payment method manually?

**Comment by jennyvbrown** [comment]
That was our issue. Thank you.
